---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: plugins/docker
  settings:
    repo: quay.io/ukhomeofficedigital/rabbitmq-alpine
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
      - latest
    when:
      event: push


- name: trivy_scan
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/trivyscanner:b82
  commands:
  - trivy --ignore-unfixed --exit-code 1 --no-progress quay.io/ukhomeofficedigital/rabbitmq-alpine:${DRONE_COMMIT_SHA}
  when:
    branch:
      exclude:
      - master
    event:
    - push
