pipeline:

  build:
    image: ukhomeoffice/drone-docker
    # repo: quay.io/ukhomeofficedigital/rabbitmq-alpine
    commands: echo $$docker_username
    secrets: [ docker_username, docker_password ]
    # registry: quay.io
    # force_tag: true
    # tags:
    #   - ${DRONE_COMMIT_SHA}
    #   - ${DRONE_BUILD_NUMBER}
    #   - latest
    when:
      event: push

  build2:
    image: ukhomeoffice/drone-docker
    # repo: quay.io/ukhomeofficedigital/rabbitmq-alpine
    commands: echo $$docker_username
    secrets: [ docker_username, docker_password ]
    # registry: quay.io
    # force_tag: true
    # tags:
    #   - ${DRONE_COMMIT_SHA}
    #   - ${DRONE_BUILD_NUMBER}
    #   - latest
    when:
      event: push
